### ISSUE TITLE
Memory leak in 2.8.21 Docker version of NewRelic infra

### ISSUE THREAD

**Issue by coolbananas118** [newrelic/infrastructure-bundle#217]
We recently upgraded from `2.2.2` to `2.8.21` on our AWS ECS service which runs the newrelic infra docker image as a side car. We had numerous task failures in various environments. Our metrics from NewRelic indicate a memory leak caused the issue because memory grows and grows until it maxes out out allocated 32M. In the old version memory remains stable for days/weeks. This is the docker image we used:
https://hub.docker.com/layers/infrastructure-bundle/newrelic/infrastructure-bundle/2.8.21/images/sha256-001010c0b72ebcede86b38647e5474dca7fef99f2808d0ebc6a582a14816ef50?context=explore

**Comment by josemore** [comment]
thanks for sharing this @coolbananas118, can you please share more details about the configuration? Any info that would help us reproduce the issue would help.

**Comment by paologallinaharbur** [comment]
@coolbananas118 
Is it happening constantly in all Newrelic instance or just from time to time to a few of them?

**Comment by coolbananas118** [comment]
Hi @josemore here is the JSON from the ECS task definition of just the sidecar portion. i can't share the main container info.
`{
	"dnsSearchDomains": null,
	"environmentFiles": null,
	"logConfiguration": {
		"logDriver": "awslogs",
		"secretOptions": null,
		"options": {
			"awslogs-group": "xxxxxxxxx",
			"awslogs-region": "us-east-2",
			"awslogs-stream-prefix": "ecs"
		}
	},
	"entryPoint": null,
	"portMappings": [],
	"command": null,
	"linuxParameters": null,
	"cpu": 64,
	"environment": [{
			"name": "ENABLE_NRI_ECS",
			"value": "true"
		},
		{
			"name": "FARGATE",
			"value": "true"
		},
		{
			"name": "NRIA_CUSTOM_ATTRIBUTES",
			"value": "{\"Name\":\"xxxxx\",\"docker_image\":\"xxxxxxxx\"\"mp:customer\":\"shd\",\"mp:environment\":\"dev\",\"mp:owner\":\"xxxxx\",\"mp:service\":\"xxxxx\"}"
		},
		{
			"name": "NRIA_IS_SECURE_FORWARD_ONLY",
			"value": "true"
		},
		{
			"name": "NRIA_OVERRIDE_HOST_ROOT",
			"value": ""
		},
		{
			"name": "NRIA_PASSTHROUGH_ENVIRONMENT",
			"value": "ECS_CONTAINER_METADATA_URI,ENABLE_NRI_ECS,FARGATE"
		}
	],
	"resourceRequirements": null,
	"ulimits": null,
	"repositoryCredentials": {
		"credentialsParameter": "xxxxxx"
	},
	"dnsServers": null,
	"mountPoints": [],
	"workingDirectory": null,
	"secrets": [{
		"valueFrom": "xxxxxx",
		"name": "NRIA_LICENSE_KEY"
	}],
	"dockerSecurityOptions": null,
	"memory": 32,
	"memoryReservation": 32,
	"volumesFrom": [],
	"stopTimeout": null,
	"image": "newrelic/infrastructure-bundle:2.2.2",
	"startTimeout": null,
	"firelensConfiguration": null,
	"dependsOn": null,
	"disableNetworking": null,
	"interactive": null,
	"healthCheck": null,
	"essential": true,
	"links": null,
	"hostname": null,
	"extraHosts": null,
	"pseudoTerminal": null,
	"user": null,
	"readonlyRootFilesystem": null,
	"dockerLabels": null,
	"systemControls": null,
	"privileged": null,
	"name": "newrelic-infra"
}`

**Comment by coolbananas118** [comment]
@paologallinaharbur we run 5 services with the side car. In Production we had 2 failures on 1 service and 1 failure on another over about 4 days so not all of them failed but we saw the memory grow on all of them so they wouldn't maxed out eventually. We had failures in non-Production but we don't have alarms there so don't have a count of how many occurrences but  as a rough guess I'd say it happened 10-20 times across all 5 services.

**Comment by paologallinaharbur** [comment]
Hello, checking the configuration I noticed two things:
 - you are still pointing do `newrelic/infrastructure-bundle:2.2.2` that used to have bundled `nri-ecs` in version [2.8.0](https://github.com/newrelic/infrastructure-bundle/releases/tag/2.8.0) the integration was removed to the bundled. Now the updated image is https://hub.docker.com/r/newrelic/nri-ecs/tags
 - why have you assigned just 32 MB of hard limit for memory? could you try increasing it?

**Comment by paologallinaharbur** [comment]
In our test environment without any load for example it consumes 38MB (above the limit set). Checking the consumptions of old versions it is true that before without any load it used to consume 20-something MBs on average.

I would recommend to update and increate the limits

**Comment by coolbananas118** [comment]
@paologallinaharbur thanks for the feedback. Sorry for the confusion. I accidentally shared the current config not the config during the failures. The only thing that was different was the version number. We allocate a very small amount of capacity to our tasks hence why we assigned only 32M. We will try increase it to see if the NR container becomes stable.

**Comment by coolbananas118** [comment]
@paologallinaharbur we increased memory to 48 and upgraded to 2.8.22 and after 1.5 days it's holding. We'll monitor for a few more days and close the ticket if all is well.

**Comment by coolbananas118** [comment]
@paologallinaharbur it's not looking so good now. After 1 week it's gradually increased from 15M to 39M. It looks likely that it'll hit out of memory once it gets near to 48M. I'm pretty certain it's not right. For example another side car we run is stable (memory plateaus). The 2.2.2 version of the New Relic docker container has always been stable. We're only running 2.8.22 in production on one service which has this issue. All other services run 2.2.2 and they are all perfectly stable at 15M.

**Comment by coolbananas118** [comment]
@paologallinaharbur can you clarify your earlier comment `you are still pointing do newrelic/infrastructure-bundle:2.2.2 that used to have bundled nri-ecs in version [2.8.0](https://github.com/newrelic/infrastructure-bundle/releases/tag/2.8.0) the integration was removed to the bundled. Now the updated image is https://hub.docker.com/r/newrelic/nri-ecs/tags`. Are you saying we are using the wrong Docker image?

**Comment by paologallinaharbur** [comment]
Hello, in the task definition I see `newrelic/infrastructure-bundle` however the new image bundling nri-ecs is `newrelic/nri-ecs`. 
Most of data is still collected since nri-bundle still have the `agent`+`nri-docker`, but you miss the medatada collected by `nri-ecs`.

**Comment by paologallinaharbur** [comment]
Thanks for reporting your findings I'll let my team know. In the meanwhile you can downgrade the solution.

**Comment by coolbananas118** [comment]
Update: we left these running and on the 9th day they ran out of memory. It really does seem to be a memory leak issue.

**Comment by rogercoll** [comment]
Thanks for the continuos feedback @coolbananas118 . We have seen that the problem starts in version 1.8.1. We are currently launching multiple modified versions of the nri-ecs image to identify the exact version of nri-bundle which is producing the issue.

We will notify you and update this issue as soon as the problem is solved.

**Comment by paologallinaharbur** [comment]
The infrastructure bundle has been updated. I am currently releasing [nri-ecs:1.9.2](https://github.com/newrelic/nri-ecs/releases/tag/v1.9.2).

You can find the image [here](https://hub.docker.com/layers/nri-ecs/newrelic/nri-ecs/1.9.2/images/sha256-6546aa178403acfc10ad769167c5fff8f76fd487f7c600b94efa496dcaa7d264?context=explore)

Feel free to reopen if running this image you still notice some issues. Moreover, thanks again for letting us know about this issue

**Comment by coolbananas118** [comment]
We've deployed 2.8.25 which has been stable for 24hrs. We'll continue to monitor.
