### ISSUE TITLE
Add support to pin digest for packages

### ISSUE THREAD

**Issue by Dentrax** [newrelic/infrastructure-bundle#305]
### Description
In current implementation, we don't do digest check of downloaded packages in order to ensure that content is not changed (tampered with or corrupted) for the corresponding package tag.

### Acceptance Criteria
1. Introduce a new `sha256` field in [integrationConfig](https://github.com/newrelic/infrastructure-bundle/blob/ece3dc47380c31d131a17d2b3b9f42f9811545fc/downloader.go#L44) struct.
2. Check the file integrity by comparing the digest after download

### Design Consideration/Limitations
Content integrity check is one of the crucial step to ensure "we always download the same content". Not having such this check would have led to significant security risks, but not limited to:
* The file in the upstream is tampered
* File is corrupted during download

### Dependencies
`-`

### Additional context
https://github.com/wolfi-dev/os/pull/2409

I'm volunteer to implement this.

/cc @gsanchezgavier @paologallinaharbur @cristianciutea

### Estimates
`S`

**Comment by gsanchezgavier** [comment]
Hi @Dentrax, thanks for the proposal and volunteering on this. 
I have some questions regarding the proposal: 
- We are not currently computing/saving the digests at building time for integrations AFAIK, did you think to compute those in some way?
- We have some rules for `renovate`  to automatically bump these versions on the bundle.yml files upon new releases, do you have in mind a way to configure renovate to also pick the new digests so automation doesn't brake?

**Comment by gsanchezgavier** [comment]
>You don't need to calculate digest at building time.

I was referring that we are not computing it as an extra step of the building process. 

>Its the shasum256 of final .tar.gz file. It should be straightforward task to do.

My question was to understand, where and when the hash will be computed. Do you propose to download the tarball and then compute it, and pin it to the bundle.yml?

I think that in order to implement this we should compute hash as an extra step of the build pipeline on each integration, and upload that information along with the tarball or perhaps better is to sign the tarball. Then the downloader could verify that digest or signature, and still rely on the tag to pin the version.

**Comment by Dentrax** [comment]
> I was referring that we are not computing it as an extra step of the building process.

It seems we're going to need it.

> Do you propose to download the tarball and then compute it, and pin it to the bundle.yml?

Actually I don't know a different way to do it. I think GitHub API does not support this. [^1] Another way is maybe pinning _commit digests_ instead of _file checksum_. 🤔 

> upload that information along with the tarball

Do you mean we should upload `checksums.txt` file as an additional artifact? We can easily get the _shasums_ of each artifact individually. But this would a bit time consuming since we have to generate and upload the `checksums.txt` in each integration we have.

> Then the downloader could verify that digest or signature, and still rely on the tag to pin the version.

Exactly!

[^1]: https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28

**Comment by Dentrax** [comment]
> Integrations are downloaded from our [bucket](https://github.com/newrelic/infrastructure-bundle/blob/master/bundle.yml?rgh-link-date=2023-06-01T09%3A30%3A38Z#L9)

I think we can write a simple script that downloads all the packages and calculates the checksums individually. Question is how should we configure the `renovate` bot to make this process in automated manner.

**Comment by brushknight** [comment]
Hello @Dentrax, after reading this thread I think we would not benefit from generating checksums after downloading the tar.gz. The integrity of the tar.gz will be checked during the un-tar attempt.

If we are talking about security concerns, then we should go for the detached signatures that should be generated and uploaded for each integration release (during the release process).
