### ISSUE TITLE
Update nrjmx to v1.6.1

### ISSUE THREAD

**Issue by Noly** [newrelic/infrastructure-bundle#43]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Build failed when updating nrjmx to v1.6.1.
Binary doesn't exist https://download.newrelic.com/infrastructure_agent/binaries/linux/noarch

## Additional context
There are many security vulnerabilities solved in last version of nrjmx. It is highly important to update to last version.

[Here](https://github.com/newrelic/infrastructure-bundle/runs/1424179348?check_suite_focus=true) more details on failure.

**Comment by paologallinaharbur** [comment]
@Noly Let us know when this is fixed to use the new version of the infra dundle
