### ISSUE TITLE
Automate or document bumping the referenced infrastructure-bundle version in nri-ecs

### ISSUE THREAD

**Issue by roobre** [newrelic/infrastructure-bundle#50]
Currently, the [ECS documentation](https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration) asks the user to deploy an AWS stack as an easy way to set up the integration. This stack uses `infrastructure-bundle`, but the template file is located in the [`nri-ecs` repo](https://github.com/newrelic/nri-ecs/blob/main/deploy/cloudformation/task/task.yaml). This has the effect of new releases of infra-bundle not being reflected in the docs for ECS, and therefore not being used by new customers.

I think it would be a good idea to automate or document this dependency, and create a workflow in which new releases of infra-bundle open a PR on the nri-ecs repo bumping this.

What are your thoughts on this?

**Comment by gsanchezgavier** [comment]
Now nri-ecs integration has it's own image based on the bundle, and all installations scripts, templates, and configuration needed are in the ecs repo.
