### ISSUE TITLE
"latest" Docker tag pointing to 2.2.3

### ISSUE THREAD

**Issue by MarkG-IEL** [newrelic/infrastructure-bundle#76]
The "latest" Docker hub tag is pointing to 2.2.3. It should be pointing to 2.5.0.

https://hub.docker.com/r/newrelic/infrastructure-bundle/tags?page=1&ordering=last_updated

**Comment by roobre** [comment]
Hi,
Thanks for noticing this! We stopped publishing `:latest` at some point for unknown reasons, but we have agreed on bringing back this behavior. I've drafted a PR fixing the pipeline to do so, we'll proceed to merge it in the following days.
